blank_issues_enabled: false
contact_links:
  - name: Diskusi Proyek
    url: https://github.com/notedavidrinaldi/palasik-iot-framework/discussions
    about: Diskusikan ide, use case, dan arah pengembangan di forum diskusi.
